### ISSUE TITLE
Bolding causes minor issues

### ISSUE THREAD

**Issue by Trainzack** [dankreider/musglyphs#4]
I noticed some issues with the font when I set it as the font for tempo markings in MuseScore. Notice the discontinuity between the eighth notes and their beam. I realized quickly that tempo markings were bolded by default, and that this was causing the issue.

I'm not sure if there really is a practical use case for bolding this font, so I don't think this bug has super high priority.

![image](https://user-images.githubusercontent.com/19575360/113691710-933b0b80-9681-11eb-9abc-52bbdfc468f2.png)
![image](https://user-images.githubusercontent.com/19575360/113692093-06dd1880-9682-11eb-9b5b-c8f275142b8d.png)

Also, I'm not sure if you had this use case in mind when creating the font, but I think the kerning between the medium parentheses and symbols like `e`  and `qe3`, could be tightened a bit.

**Comment by dankreider** [comment]
Thanks for pointing this out; both are are easy fix for the next release.

**Comment by dankreider** [comment]
I've corrected this error... there were unwanted nodes that hadn't been deleted (I had chopped the stems to lower the overall height). It's corrected now and will be pushed out in the next release.

**Comment by Trainzack** [comment]
Looks great! Though I think you missed the kerning between `qe3` and `))`, because it looks different than the kerning between `e` and `))`.

**Comment by dankreider** [comment]
You're right, thank you for catching that. I'll try to correct that for the next release.

**Comment by dankreider** [comment]
I adjusted the kerning slightly, but I opted to leave the kerning between `qe3` and `)` slightly greater.

Oh and BTW, I re-mapped `(` and `)` to be the mid-size parentheses, since they're more commonly used.
